### ISSUE TITLE
soilpsi() code comments incorrect

### ISSUE THREAD

**Issue by bpbond** [email-clm/Millennial#1]
Lines 829-831 in `main.F90` say that the sand, silt, and clay parameters are percentages, but they're actually fractions (0-1)?

See https://github.com/PNNL-TES/millenial/issues/1

**Comment by email-clm** [comment]
Hi Ben,

Sorry for the confusion, the notes show sand, silt, and clay as percentage.
But the real calculation is based on fraction (0-1). See the
https://github.com/email-clm/Millennial/blob/master/simulation/soilpara_in.

I will correct those inconsistencies.

Best,
Xiaofeng

**Comment by email-clm** [comment]
have put a note in the code
