### ISSUE TITLE
f_DOC_ATM computation not assigned correctly in decomp_century()

### ISSUE THREAD

**Issue by bpbond** [email-clm/Millennial#2]
The `f_DOC_ATM` computation is incorrectly (I think) assigned to `f_DOC_leaching` in line 956 of `main.F90`.

See 
https://github.com/PNNL-TES/millenial/issues/7#issuecomment-471092576

**Comment by email-clm** [comment]
yes, this should be noted when setting up century run with this code. 
this portion of code has been removed as this code is solely for the Millennial model.
