### ISSUE TITLE
Clarify Qmax (Eq. 11) calculation

### ISSUE THREAD

**Issue by bpbond** [email-clm/Millennial#3]
See https://github.com/PNNL-TES/millenial/issues/10

Basically, I think for clarity line 704 should be changed to
```fortran
 Qmax = 10.0 ** (0.297 * log(clay * 100.0) + 2.355 + 0.50) * 1.0 ! 1.0 is bulk density to convert Q from mg/kg to g/m2; see Eq. 11 in Abramoff et al. (2017)
```

**Comment by email-clm** [comment]
Thanks, Ben.
You are right, I will put a note to our code as well.

Xiaofeng

**Comment by email-clm** [comment]
it has been changed to 
Qmax = 10.0 ** (0.297 * log(clay * 100.0) + 2.855) * 1.35
to be consistent with the mansucript.
